{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "stornx.clusterRoleBindingName" . }}
  labels:
    {{- include "stornx.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "stornx.clusterRoleName" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "stornx.serviceAccountName" . }}
    namespace: {{ include "stornx.namespace" . }}
{{- end }}
